package com.example.pharmacy.controller;

import com.example.pharmacy.model.Medicine;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

@RestController
@RequestMapping("/medicines")
public class MedicineController {
    private final Map<Integer, Medicine> medicineMap = new ConcurrentHashMap<>();
        private int nextMedicineId = 1;

            @PostMapping
                public boolean addMedicine(@RequestBody Medicine medicine) {
                        // Assign a unique ID to the medicine
                                medicine.setMedicineId(nextMedicineId++);
                                        // Add the medicine to the map
                                                medicineMap.put(medicine.getMedicineId(), medicine);
                                                        return true;
                                                            }

                                                                @PutMapping("/{medicineId}")
                                                                    public Medicine updateMedicine(@PathVariable int medicineId, @RequestBody Medicine updatedMedicine) {
                                                                            if (medicineMap.containsKey(medicineId)) {
                                                                                        // Update the medicine details
                                                                                                    Medicine existingMedicine = medicineMap.get(medicineId);
                                                                                                                existingMedicine.setMedicineName(updatedMedicine.getMedicineName());
                                                                                                                            existingMedicine.setPrice(updatedMedicine.getPrice());
                                                                                                                                        existingMedicine.setQuantity(updatedMedicine.getQuantity());
                                                                                                                                                    existingMedicine.setDescription(updatedMedicine.getDescription());
                                                                                                                                                                return existingMedicine;
                                                                                                                                                                        }
                                                                                                                                                                                return null;
                                                                                                                                                                                    }
                                                                                                                                                                                    }
                                                                                                                                                                                    